name: Cleanup

on:
  schedule:
    - cron: '0 0 * * 0'  # Каждое воскресенье в полночь

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up cache
        run: |
          echo "🧹 Очистка кэша GitHub Actions..."
        env:
          ACTIONS_RUNNER_DEBUG: true
      - name: Remove old artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const weekAgo = new Date();
            weekAgo.setDate(weekAgo.getDate() - 7);
            
            for (const artifact of artifacts) {
              if (new Date(artifact.created_at) < weekAgo) {
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
                console.log(`Deleted artifact: ${artifact.name}`);
              }
            }